Initial deploy (PR 1)
YuriyBC/Trello-like-todo-board pull request #1
Opened 2019-01-04 04:13 UTC by YuriyBC

2019-01-08 10:06 UTC, collapserage requested changes

2019-01-08 10:06 UTC, collapserage commented on src/components/AddColumnButton.tsx
> +    toggleEditMode: any,
Please don't use `any` and `object` in typescript code, in 95% of cases they could be replaced with proper types

2019-01-08 10:06 UTC, collapserage commented on src/components/AddColumnButton.tsx
> +                               if (ev && ev.key === 'Enter') {
Try to get rid of all inline functions inside jsx that take up more than one line

2019-01-08 10:06 UTC, collapserage commented on src/components/AddColumnButton.tsx
> +        const ignoredContainer = document.getElementsByClassName(containerClass)[0];
You can use refs to access this html element
Here's a good example of how to re-structure this component https://stackoverflow.com/questions/32553158/detect-click-outside-react-component

2019-01-08 10:06 UTC, collapserage commented on src/components/AddColumnButton.tsx
> +            <div onClick={props.toggleEditMode}
Move all large jsx blocks to separate methods?

2019-01-08 10:06 UTC, collapserage commented on src/components/CartItem.tsx
> +        let MAX_LENGTH = 350;
You can set it as a default argument and move it outside this component as a helper function (or use lodash if you like, it also has throttle function and a lot of other stuff)

2019-01-08 10:06 UTC, collapserage commented on src/components/CartList.tsx
> +    const list = props.carts.map((cart: {
Interfaces shouldn't be inlined for better readability and reusability

2019-01-08 10:06 UTC, collapserage commented on src/components/CartList.tsx
> +let inputDraggedInfo = {};
Don't store data outside of your component, maybe use class component instead?

2019-01-08 10:06 UTC, collapserage commented on src/components/ColumnComponent.tsx
> +        if (!ev) return;
Please don't use short names in your code, full words (`element` instead of `el` and `event` instead of `ev`) are easier to read

2019-01-08 10:06 UTC, collapserage commented on src/components/ColumnComponent.tsx
> +        let el: any = document.getElementsByClassName('column-header__title')[0];
Try to minimise all usages of native dom access functions in react code (`getElementsByClassName`, `querySelector`, etc)
This one looks especially strange, there could be more than one column, but you access only the first one

2019-01-08 10:06 UTC, collapserage commented on src/components/CustomizeModalComponent.tsx
> +interface availibleColorsInterface {
`IAvailableColors`
Name interfaces with a capital letter (you can setup tslint with some default presets, it will really help with such codestyle inconsistencies)

2019-01-08 10:06 UTC, collapserage commented on src/components/CustomizeModalComponent.tsx
> +        const availibleColors: availibleColorsInterface = {
You can move this below interfaces and above component

2019-01-08 10:06 UTC, collapserage commented on src/components/CustomizeModalComponent.tsx
> +        let self = this;
Is it needed? Arrow function below doesn't change `this`

2019-01-08 10:06 UTC, collapserage commented on src/components/UpdateCartModal.tsx
> +        const availibleColors: availibleColorsInterface = {
Seems copy-pasted, maybe move to a separate file with `.ts` extension?

2019-01-08 10:06 UTC, collapserage commented on src/components/UpdateCartModal.tsx
> +interface UpdateCartModalInterface {
It should be `card` instead of `cart` :) Needs to be replaced in other files and file names too

2019-01-08 10:06 UTC, collapserage commented on src/components/UpdateCartModal.tsx
> +                el.style.border = '1px solid red';
Please don't modify css styles directly, use react styles instead
Maybe you can remove js validation altogether and try a simple form validation based on html attributes https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

2019-01-08 10:06 UTC, collapserage commented on src/components/containers/HeaderComponent.tsx
> +        let storageHistory: any = localStorage.getItem('history');
`render` should only display data, I think you can move getting and parsing local storage data outside of it
You should also try to always use `const` instead of `let`, it leads to a more straightforward, testable and bug-free code

2019-01-08 10:06 UTC, collapserage commented on src/styles/CustomizeModalComponent.scss
> +  //::-webkit-file-upload-button {
Remove?

2019-01-08 10:06 UTC, collapserage commented on src/components/CustomizeModalComponent.tsx
> +                                   name="ImageForm"
`imageForm`?

2019-01-08 10:21 UTC, collapserage commented on src/components/CustomizeModalComponent.tsx
> +    updateFilenameTitle(ev: HTMLInputEvent) {
`React.SyntheticEvent<HTMLInputElement>`

2019-01-10 11:53 UTC, YuriyBC commented on src/components/AddColumnButton.tsx
> +                               if (ev && ev.key === 'Enter') {
fixed

2019-01-10 11:55 UTC, YuriyBC commented on src/components/AddColumnButton.tsx
> +        const ignoredContainer = document.getElementsByClassName(containerClass)[0];
fixed

2019-01-10 11:55 UTC, YuriyBC commented on src/components/AddColumnButton.tsx
> +            <div onClick={props.toggleEditMode}
fixed

2019-01-10 11:55 UTC, YuriyBC commented on src/components/CartItem.tsx
> +        let MAX_LENGTH = 350;
fixed

2019-01-10 11:55 UTC, YuriyBC commented on src/components/UpdateCartModal.tsx
> +interface UpdateCartModalInterface {
fixed

2019-01-10 11:56 UTC, YuriyBC commented on src/components/UpdateCartModal.tsx
> +                el.style.border = '1px solid red';
fixed

2019-01-10 11:56 UTC, YuriyBC commented on src/components/containers/HeaderComponent.tsx
> +        let storageHistory: any = localStorage.getItem('history');
fixed

2019-01-10 11:57 UTC, YuriyBC commented on src/styles/CustomizeModalComponent.scss
> +  //::-webkit-file-upload-button {
fixed

2019-01-10 11:57 UTC, YuriyBC commented on src/components/CustomizeModalComponent.tsx
> +                                   name="ImageForm"
fixed

2019-01-10 11:57 UTC, YuriyBC commented on src/components/CustomizeModalComponent.tsx
> +    updateFilenameTitle(ev: HTMLInputEvent) {
fixed

2019-01-10 11:57 UTC, YuriyBC commented on src/components/CartList.tsx
> +    const list = props.carts.map((cart: {
fixed

2019-01-10 11:57 UTC, YuriyBC commented on src/components/CartList.tsx
> +let inputDraggedInfo = {};
fixed

2019-01-10 11:57 UTC, YuriyBC commented on src/components/ColumnComponent.tsx
> +        if (!ev) return;
fixed

2019-01-10 11:58 UTC, YuriyBC commented on src/components/ColumnComponent.tsx
> +        let el: any = document.getElementsByClassName('column-header__title')[0];
fixed only in components

2019-01-10 11:58 UTC, YuriyBC commented on src/components/CustomizeModalComponent.tsx
> +interface availibleColorsInterface {
Renamed all Interfaces

2019-01-10 11:59 UTC, YuriyBC commented on src/components/CustomizeModalComponent.tsx
> +        const availibleColors: availibleColorsInterface = {
done

2019-01-10 11:59 UTC, YuriyBC commented on src/components/CustomizeModalComponent.tsx
> +        let self = this;
fixed

2019-01-10 12:00 UTC, YuriyBC commented on src/components/UpdateCartModal.tsx
> +        const availibleColors: availibleColorsInterface = {
i 'm having an error when i'm trying to replace this interface to different file. Can't fix it right now. I propose to skip this issue

2019-01-10 12:02 UTC, YuriyBC commented on src/components/AddColumnButton.tsx
> +    toggleEditMode: any,
got it. Props Interfaces fixed in all project.

2019-01-10 13:06 UTC, collapserage commented on src/components/containers/HeaderComponent.tsx
> +        switch (type) {
Is this switch needed?

```
setStateFromHistory(type: string, currentClass: string) {
    if (currentClass === 'active') {
        this.props.setStateFromHistory(type)
    }
}
```

2019-01-10 13:08 UTC, collapserage commented on src/components/UpdateCardModal.tsx
> +                               onChange={($ev) => this.setForm($ev, 'title')}/>
Why `$`? :)

2019-01-14 06:46 UTC, YuriyBC commented on src/components/UpdateCardModal.tsx
> +                               onChange={($ev) => this.setForm($ev, 'title')}/>
Addictive thing from vue.js )

2019-01-14 06:50 UTC, YuriyBC commented on src/components/containers/HeaderComponent.tsx
> +        switch (type) {
No, already fixed

2019-01-14 06:51 UTC, YuriyBC commented on src/components/UpdateCardModal.tsx
> +                               onChange={($ev) => this.setForm($ev, 'title')}/>
FIxed

2019-01-31 11:44 UTC, merged